version: 3

services:
  vercel-logs:
    build: .
    container_name: vercel-logs
    volumes:
      - ./data:/usr/vercel-logs/data
    expose:
      - 8080
    restart: unless-stopped
    networks:
      - nproxy

networks:
  nproxy:
    external:
      name: nproxy
