version: "3"

services:
  vercel_logs:
    build: .
    container_name: vercel_logs
    volumes:
      - ./data:/data
    expose:
      - 8080
    restart: unless-stopped
    networks:
      - nproxy

networks:
  nproxy:
    external:
      name: nproxy
